Repository ergebnis/test-util, pull requests merged in 2020-10, with the labels that each got.

#326 Enhancement: Implement BooleanProvider
  .github/workflows/integrate.yaml
  CHANGELOG.md
  Makefile
  README.md
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  src/DataProvider/BooleanProvider.php
  src/Exception/EmptyValues.php
  src/Helper.php
  test/Unit/DataProvider/BooleanProviderTest.php
  test/Unit/Exception/EmptyValuesTest.php
  test/Unit/HelperTest.php
Labels: enhancement, merge

#327 Enhancement: Implement NullProvider
  .github/workflows/integrate.yaml
  CHANGELOG.md
  Makefile
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/NullProvider.php
  test/Unit/DataProvider/NullProviderTest.php
Labels: enhancement, merge

#328 Enhancement: Implement StringProvider
  .github/workflows/integrate.yaml
  CHANGELOG.md
  Makefile
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/StringProvider.php
  test/Unit/DataProvider/StringProviderTest.php
Labels: enhancement, merge

#329 Fix: Rename methods
  phpstan-baseline.neon
  src/DataProvider/BooleanProvider.php
  src/DataProvider/NullProvider.php
  src/DataProvider/StringProvider.php
  src/Helper.php
  test/Unit/HelperTest.php
Labels: bug, merge

#330 Enhancement: Provide example for composition of data providers
  README.md
Labels: enhancement, merge

#331 Fix: Add StringProvider to list in README.md
  README.md
Labels: bug, merge

#332 Fix: Test data providers directly
  .github/workflows/integrate.yaml
  Makefile
  phpstan-baseline.neon
  phpstan.neon
  test/Unit/DataProvider/AbstractProviderTestCase.php
  test/Unit/DataProvider/BooleanProviderTest.php
  test/Unit/DataProvider/NullProviderTest.php
  test/Unit/DataProvider/StringProviderTest.php
Labels: bug, merge

#333 Fix: Remove empty list item
  README.md
Labels: bug, merge

#334 Fix: Rename data provider
  CHANGELOG.md
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/BoolProvider.php
  test/Unit/DataProvider/BoolProviderTest.php
  test/Unit/Exception/InvalidExcludeClassNameTest.php
  test/Unit/HelperTest.php
Labels: bug, merge

#335 Enhancement: Implement IntProvider
  .github/workflows/integrate.yaml
  CHANGELOG.md
  Makefile
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/IntProvider.php
  test/Unit/DataProvider/IntProviderTest.php
Labels: enhancement, merge

#336 Fix: Test provided values individually
  .github/workflows/integrate.yaml
  Makefile
  phpstan-baseline.neon
  psalm-baseline.xml
  test/Unit/DataProvider/AbstractProviderTestCase.php
  test/Unit/DataProvider/IntProviderTest.php
  test/Unit/DataProvider/StringProviderTest.php
Labels: bug, merge

#337 Enhancement: Extract specifications
  .github/workflows/integrate.yaml
  Makefile
  phpstan-baseline.neon
  psalm-baseline.xml
  test/Unit/DataProvider/AbstractProviderTestCase.php
  test/Unit/DataProvider/BoolProviderTest.php
  test/Unit/DataProvider/IntProviderTest.php
  test/Unit/DataProvider/NullProviderTest.php
  test/Unit/DataProvider/StringProviderTest.php
  test/Util/DataProvider/Specification/Closure.php
  test/Util/DataProvider/Specification/Identical.php
  test/Util/DataProvider/Specification/Pattern.php
  test/Util/DataProvider/Specification/Specification.php
Labels: enhancement, merge

#338 Fix: Provide all kinds of string values from StringProvider::arbitrary()
  README.md
  src/DataProvider/StringProvider.php
  test/Unit/DataProvider/StringProviderTest.php
Labels: bug, merge

#340 Fix: Add IntProvider to list
  README.md
Labels: bug, merge

#339 Enhancement: Implement DataProvider\StringProvider::trimmed()
  .github/workflows/integrate.yaml
  Makefile
  README.md
  psalm-baseline.xml
  src/DataProvider/StringProvider.php
  test/Unit/DataProvider/StringProviderTest.php
Labels: enhancement, merge

#341 Enhancement: Implement DataProvider\FloatProvider
  .github/workflows/integrate.yaml
  CHANGELOG.md
  Makefile
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/FloatProvider.php
  test/Unit/DataProvider/FloatProviderTest.php
Labels: enhancement, merge

#343 Enhancement: Implement DataProvider\ObjectProvider
  .php_cs
  CHANGELOG.md
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/ObjectProvider.php
  test/Unit/DataProvider/ObjectProviderTest.php
  test/Util/DataProvider/Specification/Equal.php
Labels: enhancement, merge

#342 Fix: Make clear, values are not empty
  README.md
Labels: bug

#344 Enhancement: Implement DataProvider\ResourceProvider
  CHANGELOG.md
  README.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/DataProvider/ResourceProvider.php
  test/Unit/DataProvider/ResourceProviderTest.php
Labels: enhancement, merge

#360 Enhancement: Synchronize with ergebnis/php-library-template
  .gitattributes
  .github/CODEOWNERS
  .github/actions/composer/composer/determine-cache-directory/action.yaml
  .github/actions/composer/composer/install/run.sh
  .github/dependabot.yaml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  .phive/composer-require-checker
  .php_cs
  Makefile
  phive.xml
Labels: enhancement, merge
